### ISSUE TITLE
Does not work with current versions of Sinatra and Authlogic

### ISSUE THREAD

**Issue by amikula** [ehsanul/Sinatra-Authlogic-Template#1]
I get an error when trying to start this up with Sinatra 0.9.4 and Authlogic 2.1.3.  See below for the error.  Changing SinatraAdapter to a module and removing the inheritance doesn't solve the problem, and I can't find AuthLogic documentation on current methods for activating adapters.

Here's the error:

./sinadapt.rb:7: SinatraAdapter is not a class (TypeError)
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from sin-auth-template.rb:1
        from sin-auth-template.rb:1:in`each'
        from sin-auth-template.rb:1
./sinadapt.rb:7: SinatraAdapter is not a class (TypeError)
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from sin-auth-template.rb:1
        from sin-auth-template.rb:1:in`each'
        from sin-auth-template.rb:1

**Comment by ehsanul** [comment]
Sinatra version is fine, but the Authlogic version needs to be no more than 2.1.1 with this code. Latest version has a bunch of changes that make it incompatible with the Sinatra adapter here. Also, there seems to be official support from Authlogic coming soon for Sinatra, so look out for that.

**Comment by amikula** [comment]
Now works fine with latest versions of AuthLogic and Sinatra.
